### ISSUE TITLE
Suggestion for the project

### ISSUE THREAD

**Issue by PaulDBM** [sinarest1608/Shop-Problem#4]
Hi! I noticed that you write the file names in differents methods in whole project. I suggest to take this file names and save in a class as static fields. This change can let you to improve the file organization.

Thanks for read this suggestion. Have a good day!

**Comment by sinarest1608** [comment]
Hey Paul!
Thanks for the suggestion. I wrote this program about a year ago and didn't update it frequently. I'll surely update keeping in mind your suggestion. 

Thanks!
